### ISSUE TITLE
Add `random` method to `ApplicationRecord`

### ISSUE THREAD

**Issue by jmejia** [VictoriaVasys/rales_engine#6]
@VictoriaVasys @jwpincus The code in your random controllers will lead to some repetition. So instead of this:

```ruby
  def show
    render json:  Invoice.order("RANDOM()").first
  end
```

I'd love to see something like this instead:

```ruby
  def show
    render json: Invoice.random
  end
```

We could define this on each model but that would also lead to repetition. `order("RANDOM()")` is specific to Postgres. If we ever decided to change our database, we'd need to find all occurrences of `order("RANDOM()")` and change them. If define a method called `random` in `/app/models/application_record.rb` then we would only need to update in one place.

**Comment by VictoriaVasys** [comment]
We included the #random method in ApplicationRecord. Thanks for the suggestion!
